int _putchar(char c);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_strchr(char *s, charc);
unsigned int _strspn(char *s, char *accept);
char *_strpbrk(char *s, char *accept);
char * strstr(char *haystack, char *needle);
void print chessboard(char (*a)[8]);
void set_string(char **s, char *to);
void print_diagsums(int *a, int size);
